# Generated by Django 5.0.6 on 2024-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketeer', '0002_ticketeertask_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketeertask',
            name='status',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=10),
        ),
    ]
