# Generated by Django 5.0.6 on 2024-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketeer', '0003_alter_ticketeertask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketeertask',
            name='prio',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=10),
        ),
    ]
