# Generated by Django 5.0.6 on 2024-06-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketeer', '0005_alter_ticketeertask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketeertask',
            name='done',
        ),
    ]
